name: Build Android APK And Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup Environment
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          GITHUB_API_URL: ${{ secrets.GIT_API_URL }}
        run: echo "Environment variables set"

      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > spendwise-release-key.jks

      - name: Install Yarn
        run: npm install -g yarn

      - name: Check if Vite is installed
        id: check-vite
        run: yarn list vite || echo 'vite_not_installed=true' >> $GITHUB_OUTPUT

      - name: Install Vite
        if: steps.check-vite.outputs.vite_not_installed == 'true'
        run: yarn add vite

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        id: cache-yarn
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        if: steps.cache-yarn.outputs.cache-hit != 'true'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: cd android && chmod +x ./gradlew

      - name: Get previous tag
        id: previous_tag
        run: echo "PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")" >> $GITHUB_OUTPUT

      - name: Determine new version & update package.json
        id: update_version
        run: |
          PREV_TAG="${{ steps.previous_tag.outputs.PREVIOUS_TAG }}"
          CUR_VERSION="${{ steps.get_version.outputs.VERSION }}"

          # Chuyển đổi thành số nguyên để so sánh
          prev_numeric=$(echo $PREV_TAG | awk -F. '{ printf("%d%03d%03d\n", $1, $2, $3) }')
          cur_numeric=$(echo $CUR_VERSION | awk -F. '{ printf("%d%03d%03d\n", $1, $2, $3) }')

          if [ "$cur_numeric" -le "$prev_numeric" ]; then
            IFS='.' read -r -a parts <<< "$PREV_TAG"
            PATCH=$((parts[2] + 1))
            NEW_VERSION="${parts[0]}.${parts[1]}.$PATCH"
            echo "Current version ($CUR_VERSION) is not greater than previous tag ($PREV_TAG). Bumping to $NEW_VERSION."
          else
            NEW_VERSION="$CUR_VERSION"
            echo "Keeping version as $NEW_VERSION."
          fi

          # Cập nhật package.json
          jq --arg new_version "$NEW_VERSION" '.version=$new_version' package.json > package.tmp.json && mv package.tmp.json package.json

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit updated package.json
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add package.json
          git commit -m "chore: auto-bump version to ${{ steps.update_version.outputs.NEW_VERSION }}"
          git push
        continue-on-error: true

      - name: Build Source
        run: yarn build

      - name: Set Version
        run: yarn run version

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      - name: Sign APK
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks spendwise-release-key.jks \
            --ks-pass pass:${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
            --out android/app/build/outputs/apk/release/SpendWise-${{ steps.get_version.outputs.VERSION }}.apk \
            android/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Generate changelog
        id: changelog
        run: |
          CHANGELOG=$(git log --no-merges --pretty=format:"- %s" ${{ steps.previous_tag.outputs.PREVIOUS_TAG }}..HEAD)
          COMPARE_URL="https://github.com/${{ github.repository }}/compare/${{ steps.previous_tag.outputs.PREVIOUS_TAG }}...main"
      
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="No changes in this release."
          fi
      
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "See full changes: $COMPARE_URL" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: 'v${{ steps.get_version.outputs.VERSION }}'
          name: 'SpendWise v${{ steps.get_version.outputs.VERSION }}'
          body: |
            Change log:
            ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
          files: android/app/build/outputs/apk/release/SpendWise-${{ steps.get_version.outputs.VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
